name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and Test with Maven
        run: mvn -B clean test

      - name: SonarQube Scan
        run: |
           mvn -B verify sonar:sonar \
            -Dsonar.projectKey=hoverla-team-2023_HoverlaBring_AYwIBAvijYd-lSknBhZO \
            -Dsonar.projectName='HoverlaBring' \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}